//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVM_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Visits = new HashSet<Visits>();
        }
    
        public int IDDoctor { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public int IDSpecialisation { get; set; }
        public System.TimeSpan WorkStart { get; set; }
        public System.TimeSpan WorkEnd { get; set; }
        public System.DateTime DateOfBith { get; set; }
        public string Street { get; set; }
        public string HomeNr { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
    
        public virtual Specialisation Specialisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
